#!/bin/bash

./mill examples.fragment.basics.colour-constants.fullLinkJS
./mill examples.fragment.basics.colour-interpolators.fullLinkJS
./mill examples.fragment.basics.colours.fullLinkJS
./mill examples.fragment.basics.minimal.fullLinkJS
./mill examples.fragment.demos.campfire.fullLinkJS
./mill examples.fragment.demos.glowing-star.fullLinkJS
./mill examples.fragment.demos.pulsingbox.fullLinkJS
./mill examples.fragment.noise.cellular-noise.fullLinkJS
./mill examples.fragment.noise.classic-perlin-noise.fullLinkJS
./mill examples.fragment.noise.gradient-noise.fullLinkJS
./mill examples.fragment.noise.simplex-noise.fullLinkJS
./mill examples.fragment.noise.white-noise.fullLinkJS
./mill examples.fragment.patterns.grid.fullLinkJS
./mill examples.fragment.patterns.rainbow.fullLinkJS
./mill examples.fragment.patterns.simple-voronoi.fullLinkJS
./mill examples.fragment.patterns.stripes.fullLinkJS
./mill examples.fragment.patterns.wavy-stripes.fullLinkJS
./mill examples.fragment.sdf.box.fullLinkJS
./mill examples.fragment.sdf.circle.fullLinkJS
./mill examples.fragment.sdf.hexagon.fullLinkJS
./mill examples.fragment.sdf.segment.fullLinkJS
./mill examples.fragment.sdf.star.fullLinkJS
./mill examples.fragment.sdf.triangle.fullLinkJS
./mill examples.fragment.shapes.doughnut.fullLinkJS
./mill examples.fragment.shapes.metaballs.fullLinkJS
./mill examples.fragment.textures.basic-texture-use.fullLinkJS
./mill examples.fragment.textures.blending-textures.fullLinkJS
./mill examples.fragment.textures.specifying-texture-coords.fullLinkJS
./mill examples.language-features.imports.fullLinkJS
./mill examples.language-features.ubos.fullLinkJS
./mill examples.vertex.manipulatinguvs.fullLinkJS
./mill examples.vertex.minimal.fullLinkJS
./mill examples.vertex.movingvertices.fullLinkJS
./mill shadertoy.default.fullLinkJS
./mill shadertoy.plasma.fullLinkJS
./mill shadertoy.seascape.fullLinkJS
